# Generated by Django 5.2.4 on 2025-08-05 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamiento', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento', to='usuarios.pacienteprofile', verbose_name='Paciente'),
        ),
    ]
