# Generated by Copilot - datos iniciales para Medicamento y Tratamiento
from django.db import migrations

def crear_medicamentos_y_tratamientos(apps, schema_editor):
    Medicamento = apps.get_model('tratamiento', 'Medicamento')
    Tratamiento = apps.get_model('tratamiento', 'Tratamiento')
    PacienteProfile = apps.get_model('usuarios', 'PacienteProfile')
    EpisodioCefalea = apps.get_model('evaluacion_diagnostico', 'EpisodioCefalea')

    # Crear medicamentos
    ibuprofeno = Medicamento.objects.create(
        nombre='Ibuprofeno', dosis='400mg', caracteristica='', hora_de_inicio='08:00', frecuencia_horas=8, duracion_dias=5
    )
    paracetamol = Medicamento.objects.create(
        nombre='Paracetamol', dosis='500mg', caracteristica='', hora_de_inicio='09:00', frecuencia_horas=12, duracion_dias=3
    )
    aspirina = Medicamento.objects.create(
        nombre='Aspirina', dosis='100mg', caracteristica='', hora_de_inicio='07:00', frecuencia_horas=24, duracion_dias=2
    )

    # NOTA: Para asociar tratamientos a pacientes y episodios, deben existir instancias previas
    # Aquí se asume que existen al menos 3 pacientes y 3 episodios
    pacientes = list(PacienteProfile.objects.all()[:3])
    episodios = list(EpisodioCefalea.objects.all()[:3])
    if len(pacientes) < 3 or len(episodios) < 3:
        return  # No se crean tratamientos si no hay suficientes datos

    t1 = Tratamiento.objects.create(
        paciente=pacientes[0], episodio=episodios[0], fecha_inicio=None,
        recomendaciones=["rutina_sueno"]
    )
    t2 = Tratamiento.objects.create(
        paciente=pacientes[1], episodio=episodios[1], fecha_inicio=None,
        recomendaciones=["hidratacion"]
    )
    t3 = Tratamiento.objects.create(
        paciente=pacientes[2], episodio=episodios[2], fecha_inicio=None,
        recomendaciones=["control_estres"]
    )

    t1.medicamentos.add(ibuprofeno)
    t2.medicamentos.add(paracetamol)
    t3.medicamentos.add(aspirina)

class Migration(migrations.Migration):
    dependencies = [
        ('tratamiento', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('evaluacion_diagnostico', '0002_pregunta_alter_episodiocefalea_anticonceptivos_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_medicamentos_y_tratamientos),
    ]
